export const TournamentFormModel = {
  // Step 1 fields
  name: '',
  eventDateTime: '',
  registrationStartTime: '',
  venueName: '',
  courtsNumber: '',
  organizationName: '',
  paymentMethod: '',
  matchStartTime: '',
  estimatedEndTime: '',
  venueAddress: '',
  matchOverview: '',
  organizer: '',
  administrator: '',
  sponsor: '',
  eventCategory: '',
  daysSchedule: '',
  receptionPeriod: '',
  competitionFormat: '',
  maxParticipants: '',
  competitionRules: '',
  ballType: '',
  participationEligibility: '',
  participationPaymentMethod: '',
  applicationMethod: '',
  applicationDeadline: '',
  pairingSelectionMethod: '',
  awardDetails: '',
  memberChanges: '',
  multipleEventsEntry: '',
  cancellationAfterApplication: '',
  participationFee: '',
  inquiryContactInfo: '',
  announcements: '',
  organizersURL: '',
  notes: '',
  // Step 2 fields
  field1Step2: '',
  field2Step2: '',
  // Step 3 fields
  field1Step3: '',
  field2Step3: '',
  // Add other fields for subsequent steps...
};
